# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

steps:
- powershell: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- powershell: docker run --detach --publish 8000:8000 -h $(imageName) --name ps_serv psrest
  displayName: 'docker run'
