# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'vs2017-win2016'

variables:
  imageName: 'psrest:$(build.buildId)'

steps:
- powershell: $(build)
  displayName: 'Build Var'
- powershell: powershell -file .\server.ps1
  displayName: 'Start Listener'
- powershell: powershell -file .\dockertest.ps1
  displayName: 'Test API Locally'
- powershell: docker build -f Dockerfile -t $(imageName) $PWD.Path
  displayName: 'Docker Build'
- powershell: docker run --publish 8000:8000 -h psrestapi $(imageName)
  displayName: 'Docker Run'
